{
 "title": "XTDB",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "XTDB - Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query - Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "expr": "query_timer_seconds_count", "legendFormat": "{{node_id}}" }
     ]
    },
    {
     "title": "Transactions - Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      { "expr": "tx_op_timer_seconds_count", "legendFormat": "{{node_id}}" }
     ]
    },
    {
     "title": "Query - Timer (Max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "query_timer_seconds_max", "legendFormat": "{{node_id}}" }
     ]
    },
    {
     "title": "Transactions - Timer (Max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "tx_op_timer_seconds_max", "legendFormat": "{{node_id}}" }
     ]
    },
    {
     "title": "Query - Timer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "query_timer_seconds",
       "legendFormat": "{{node_id}} - {{quantile}} quantile"
      }
     ]
    },
    {
     "title": "Transactions - Timer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "tx_op_timer_seconds",
       "legendFormat": "{{node_id}} - {{quantile}} quantile"
      }
     ]
    }
   ]
  },
  {
   "title": "XTDB - JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM - Heap Usage (Average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg by(node_id) (jvm_memory_committed_bytes)",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Heap Usage (Max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max by(node_id) (jvm_memory_committed_bytes)",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Buffer Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by(node_id) (jvm_buffer_memory_used_bytes)",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "JVM - Live Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      { "expr": "jvm_threads_live_threads", "legendFormat": "{{node_id}}" }
     ]
    },
    {
     "title": "JVM - Thread States",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "targets": [
      { "expr": "jvm_threads_states_threads", "legendFormat": "{{node_id}} - {{state}}" }
     ]
    }
   ]
  },
  {
   "title": "XTDB - Direct Allocated Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "XTDB - Buffer Pool Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "buffer_pool_allocator_allocated_memory_bytes",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Compactor Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "compactor_allocator_allocated_memory_bytes",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Indexer Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "indexer_allocator_allocated_memory_bytes",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Live Index Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "live_index_allocator_allocated_memory_bytes",
       "legendFormat": "{{node_id}}"
      }
     ]
    },
    {
     "title": "XTDB - Log Watcher Allocated Memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "watcher_allocator_allocated_memory_bytes",
       "legendFormat": "{{node_id}}"
      }
     ]
    }
   ]
  }
 ]
}