apiVersion: v1
kind: Service
metadata:
  name: {{ include "xtdb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "xtdb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: pgwire
      protocol: TCP
      port: {{ .Values.service.pgwirePort }}
      targetPort: pgwire
    - name: http
      protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: http
  selector: {{- include "xtdb.selectorLabels" . | nindent 4 }}
